package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/cloudfoundry/bosh-softlayer-cpi/softlayer/pool/client/vm"
)

// Default soft layer VM pool HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new soft layer VM pool HTTP client.
func NewHTTPClient(formats strfmt.Registry) *SoftLayerVMPool {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("vps.swagger.io", "/v2", []string{"http"})
	return New(transport, formats)
}

// New creates a new soft layer VM pool client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *SoftLayerVMPool {
	cli := new(SoftLayerVMPool)
	cli.Transport = transport

	cli.VM = vm.New(transport, formats)

	return cli
}

// SoftLayerVMPool is a client for soft layer VM pool
type SoftLayerVMPool struct {
	VM *vm.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *SoftLayerVMPool) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.VM.SetTransport(transport)

}
