package instance

import (
	bosl "bosh-softlayer-cpi/softlayer/client"
	boshlog "github.com/cloudfoundry/bosh-utils/logger"
)

const softlayerVirtualGuestServiceLogTag = "SoftlayerVirtualGuestService"
const googleInstanceNamePrefix = "vm"
const googleInstanceDescription = "Instance managed by BOSH"
const blobstoreTypeDav = "dav"
const rootUser = "root"
const volumePathPrefix = "/dev/mapper"

const EtcIscsidConfTemplate = `# Generated by bosh-agent
node.startup = automatic
node.session.auth.authmethod = CHAP
node.session.auth.username = {{.Username}}
node.session.auth.password = {{.Password}}
discovery.sendtargets.auth.authmethod = CHAP
discovery.sendtargets.auth.username = {{.Username}}
discovery.sendtargets.auth.password = {{.Password}}
node.session.timeo.replacement_timeout = 120
node.conn[0].timeo.login_timeout = 15
node.conn[0].timeo.logout_timeout = 15
node.conn[0].timeo.noop_out_interval = 10
node.conn[0].timeo.noop_out_timeout = 15
node.session.iscsi.InitialR2T = No
node.session.iscsi.ImmediateData = Yes
node.session.iscsi.FirstBurstLength = 262144
node.session.iscsi.MaxBurstLength = 16776192
node.conn[0].iscsi.MaxRecvDataSegmentLength = 65536
`

type SoftlayerVirtualGuestService struct {
	softlayerClient bosl.Client
	logger          boshlog.Logger
}

func NewSoftLayerVirtualGuestService(
	softlayerClient bosl.Client,
	logger boshlog.Logger,
) SoftlayerVirtualGuestService {
	return SoftlayerVirtualGuestService{
		softlayerClient: softlayerClient,
		logger:          logger,
	}
}

type Mount struct {
	PartitionPath string
	MountPoint    string
}

type DavConfig map[string]interface{}
