package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteVMParams creates a new DeleteVMParams object
// with the default values initialized.
func NewDeleteVMParams() *DeleteVMParams {
	var ()
	return &DeleteVMParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVMParamsWithTimeout creates a new DeleteVMParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteVMParamsWithTimeout(timeout time.Duration) *DeleteVMParams {
	var ()
	return &DeleteVMParams{

		timeout: timeout,
	}
}

// NewDeleteVMParamsWithContext creates a new DeleteVMParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteVMParamsWithContext(ctx context.Context) *DeleteVMParams {
	var ()
	return &DeleteVMParams{

		Context: ctx,
	}
}

/*DeleteVMParams contains all the parameters to send to the API endpoint
for the delete Vm operation typically these are written to a http.Request
*/
type DeleteVMParams struct {

	/*Cid
	  vm id to delete

	*/
	Cid int32

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the delete Vm params
func (o *DeleteVMParams) WithTimeout(timeout time.Duration) *DeleteVMParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete Vm params
func (o *DeleteVMParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete Vm params
func (o *DeleteVMParams) WithContext(ctx context.Context) *DeleteVMParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete Vm params
func (o *DeleteVMParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithCid adds the cid to the delete Vm params
func (o *DeleteVMParams) WithCid(cid int32) *DeleteVMParams {
	o.SetCid(cid)
	return o
}

// SetCid adds the cid to the delete Vm params
func (o *DeleteVMParams) SetCid(cid int32) {
	o.Cid = cid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVMParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param cid
	if err := r.SetPathParam("cid", swag.FormatInt32(o.Cid)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
