package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetVMByCidParams creates a new GetVMByCidParams object
// with the default values initialized.
func NewGetVMByCidParams() *GetVMByCidParams {
	var ()
	return &GetVMByCidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVMByCidParamsWithTimeout creates a new GetVMByCidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVMByCidParamsWithTimeout(timeout time.Duration) *GetVMByCidParams {
	var ()
	return &GetVMByCidParams{

		timeout: timeout,
	}
}

// NewGetVMByCidParamsWithContext creates a new GetVMByCidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVMByCidParamsWithContext(ctx context.Context) *GetVMByCidParams {
	var ()
	return &GetVMByCidParams{

		Context: ctx,
	}
}

/*GetVMByCidParams contains all the parameters to send to the API endpoint
for the get Vm by cid operation typically these are written to a http.Request
*/
type GetVMByCidParams struct {

	/*Cid
	  ID of vm that needs to be fetched

	*/
	Cid int32

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get Vm by cid params
func (o *GetVMByCidParams) WithTimeout(timeout time.Duration) *GetVMByCidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Vm by cid params
func (o *GetVMByCidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Vm by cid params
func (o *GetVMByCidParams) WithContext(ctx context.Context) *GetVMByCidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Vm by cid params
func (o *GetVMByCidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithCid adds the cid to the get Vm by cid params
func (o *GetVMByCidParams) WithCid(cid int32) *GetVMByCidParams {
	o.SetCid(cid)
	return o
}

// SetCid adds the cid to the get Vm by cid params
func (o *GetVMByCidParams) SetCid(cid int32) {
	o.Cid = cid
}

// WriteToRequest writes these params to a swagger request
func (o *GetVMByCidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param cid
	if err := r.SetPathParam("cid", swag.FormatInt32(o.Cid)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
