// This file was generated by counterfeiter
package fakes

import "sync"

type FakeSSHClient struct {
	OutputStub        func(cmd string) ([]byte, error)
	outputMutex       sync.RWMutex
	outputArgsForCall []struct {
		cmd string
	}
	outputReturns struct {
		result1 []byte
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSSHClient) Output(cmd string) ([]byte, error) {
	fake.outputMutex.Lock()
	fake.outputArgsForCall = append(fake.outputArgsForCall, struct {
		cmd string
	}{cmd})
	fake.recordInvocation("Output", []interface{}{cmd})
	fake.outputMutex.Unlock()
	if fake.OutputStub != nil {
		return fake.OutputStub(cmd)
	} else {
		return fake.outputReturns.result1, fake.outputReturns.result2
	}
}

func (fake *FakeSSHClient) OutputCallCount() int {
	fake.outputMutex.RLock()
	defer fake.outputMutex.RUnlock()
	return len(fake.outputArgsForCall)
}

func (fake *FakeSSHClient) OutputArgsForCall(i int) string {
	fake.outputMutex.RLock()
	defer fake.outputMutex.RUnlock()
	return fake.outputArgsForCall[i].cmd
}

func (fake *FakeSSHClient) OutputReturns(result1 []byte, result2 error) {
	fake.OutputStub = nil
	fake.outputReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeSSHClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.outputMutex.RLock()
	defer fake.outputMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeSSHClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
