---
platform: linux
image: docker:///posijon/slci

inputs:
  - name: bosh-softlayer-cpi
    path: gopath/src/github.com/maximilien/bosh-softlayer-cpi

run:
  path: gopath/src/github.com/maximilien/bosh-softlayer-cpi/bin/build