---
groups:
  - name: bosh-softlayer-cpi-release-wip
    jobs:
      - build-candidate
      - bats-ubuntu
      - promote-candidate

jobs:
- name: build-candidate
  serial: true
  plan:
  - aggregate:
    - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-in}
    - {trigger: false, get: version-semver, params: {bump: patch}}

  - put: version-semver
    params: {file: version-semver/number}

  - task: build
    file: bosh-cpi-release/ci/tasks/build-candidate.yml

  - put: bosh-cpi-dev-artifacts
    params: {file: candidate/*.tgz}

- name: bats-ubuntu
  plan:
  - aggregate:
    - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
    - {trigger: false,                            get: bosh-cpi-release, resource: bosh-cpi-release-in}
    - {trigger: false,                            get: bats}
    - {trigger: false,                            get: bosh-init}
    - {trigger: false,                            get: stemcell, resource: softlayer-ubuntu-stemcell}
    - {trigger: false,                            get: stemcell-version}
    - {trigger: true,  passed: [build-candidate], get: version-semver, resource: version-semver}
    - {trigger: false,                            get: bosh-release}

  - task: setup-director
    file: bosh-cpi-release/ci/tasks/setup-director.yml
    params:
      BASE_OS:                    ubuntu
      SL_USERNAME:                {{softlayer_username}}
      SL_API_KEY:                 {{softlayer_api_key}}
      SL_DATACENTER:              {{softlayer_datacenter}}
      SL_VLAN_PUBLIC:             {{softlayer_vlan_public}}
      SL_VLAN_PRIVATE:            {{softlayer_vlan_private}}
      SL_VM_NAME_PREFIX:          {{softlayer_director_name_prefix}}

  - task: run-bats
    file: bosh-cpi-release/ci/tasks/run-bats.yml
    params:
      BASE_OS:                    ubuntu
      BAT_VCAP_PASSWORD:          {{bat_vcap_password}}
      BAT_SECOND_STATIC_IP:       {{bat_second_static_ip}}
      SL_DATACENTER:              {{softlayer_datacenter}}
      SL_VLAN_PUBLIC:             {{softlayer_vlan_public}}
      SL_VLAN_PRIVATE:            {{softlayer_vlan_private}}
      SL_VM_NAME_PREFIX:          {{softlayer_bats_name_prefix}}

  - task: teardown-director
    file: bosh-cpi-release/ci/tasks/teardown-director.yml

- name: promote-candidate
  plan:
  - aggregate:
    - {trigger: true,  get: bosh-cpi-dev-artifacts, passed: [bats-ubuntu]}
    - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-out}
    - {trigger: false, get: release-version-semver, params: {bump: patch}}

  - task: promote
    file: bosh-cpi-release/ci/tasks/promote-candidate.yml
    params:
      S3_ACCESS_KEY_ID:     {{s3_access_key__primary}}
      S3_SECRET_ACCESS_KEY: {{s3_secret_key__primary}}

  - put: bosh-cpi-release-out
    params: {repository: promoted/repo, rebase: true, tag_prefix: "v", tag: promoted/integer_version}

  - put: release-version-semver
    params: {file: release-version-semver/number}

  - put: bosh-cpi-final-artifacts
    params: {file: promoted/repo/releases/bosh-softlayer-cpi/*.tgz}

resources:
- name: bosh-cpi-dev-artifacts
  type: s3
  source:
    regexp: bosh-softlayer-cpi-(\d+\.\d+\.\d+)\.tgz
    bucket: {{s3_pipeline_bucket}}
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

- name: bosh-cpi-final-artifacts
  type: s3
  source:
    regexp: bosh-softlayer-cpi-(\d+\.\d+\.\d+)\.tgz
    bucket: {{s3_pipeline_bucket}}
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

- name: bosh-cpi-release-in
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/bosh-softlayer-cpi-release.git
    branch: wip_softlayer_pool
    private_key: {{github_promote_private_key}}
    ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

- name: bosh-cpi-release-out
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/bosh-softlayer-cpi-release.git
    branch: wip_softlayer_pool
    private_key: {{github_promote_private_key}}

- name: version-semver
  type: semver
  source:
    key:               current-version # dev-release version
    bucket:            {{s3_pipeline_bucket}}
    access_key_id:     {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

- name: release-version-semver
  type: semver
  source:
    key:               release-version-v2
    bucket:            {{s3_pipeline_bucket}}
    access_key_id:     {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    initial_version: 2.0.0

- name: bosh-release
  type: bosh-io-release
  source:
      repository: cloudfoundry/bosh

- name: bosh-init
  type: s3
  source:
    regexp: bosh-init-([0-9.]+)-linux-amd64
    bucket: dev-bosh-softlayer-cpi-stemcells
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

- name: bats
  type: git
  source:
    uri: git@github.com:jianqiu/bosh-acceptance-tests.git
    branch: bosh_v2
    private_key: {{github_promote_private_key}}

- name: softlayer-ubuntu-stemcell
  type: s3
  source:
    bucket: bosh-softlayer-stemcells-bluemix
    regexp: light-bosh-stemcell-([0-9.]+)-softlayer-xen-ubuntu-trusty-go_agent\.tgz
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

- name: stemcell-version
  type: semver
  source:
    key: stemcell-version
    bucket: {{s3_candidate_stemcell_bucket}}
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}