---
groups:
  - name: lite-bosh-softlayer-cpi-release
    jobs:
      - build-candidate
      - run-lifecycle
      - bats-ubuntu
      - promote-candidate

shared:
  - &deploy-director
    task: deploy-director
    file: bosh-cpi-release/ci/bats/tasks/deploy-director-softlayer.yml
    params:
      BAT_INFRASTRUCTURE:      softlayer
      BOSH_CLIENT:             {{stemcell-test-director-username}}
      BOSH_CLIENT_SECRET:      {{stemcell-test-director-password}}
      BOSH_SL_USERNAME:        {{softlayer-username}}
      BOSH_SL_API_KEY:         {{softlayer-api-key}}
      BOSH_SL_DATACENTER:      {{softlayer-datacenter}}
      BOSH_SL_VLAN_PUBLIC:     {{softlayer-vlan-public}}
      BOSH_SL_VLAN_PRIVATE:    {{softlayer-vlan-private}}
      BOSH_SL_VM_DOMAIN:       {{softlayer-vm-domain}}
      BOSH_SL_VM_NAME_PREFIX:  {{softlayer-director-name-prefix}}
      REGISTRY_PASSWORD:       {{registry_password}}

  - &prepare-bats-config
    task: prepare-bats
    file: bosh-cpi-release/ci/bats/iaas/softlayer/prepare-bats-config.yml
    params: &prepare-bats-params
      BAT_VCAP_PASSWORD:      {{bat-vcap-password}}
      SL_DATACENTER:          {{softlayer-datacenter}}
      SL_VLAN_PRIVATE:        {{softlayer-vlan-private}}
      SL_VLAN_PUBLIC:         {{softlayer-vlan-public}}
      SL_VM_DOMAIN:           {{softlayer-vm-domain}}
      SL_VM_NAME_PREFIX:      bats-experimental
      STEMCELL_NAME:          bosh-softlayer-xen-ubuntu-trusty-go_agent

  - &run-bats
    task: run-bats
    file: bats/ci/tasks/run-bats.yml

  - &teardown
    task: teardown
    file: bosh-cpi-release/ci/bats/tasks/destroy-director.yml

jobs:
  - name: build-candidate
    serial: true
    plan:
    - aggregate:
      - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-in}
      - {trigger: false, get: version-semver, params: {bump: patch}}
      - {trigger: false, get: bosh-cli, resource: bosh-cli}

    - task: build
      file: bosh-cpi-release/ci/tasks/build-candidate.yml

    - put: version-semver
      params: {file: version-semver/number}

    - put: bosh-cpi-dev-artifacts
      params: {file: candidate/*.tgz}

  - name: run-lifecycle
    serial: true
    plan:
    - aggregate:
      - {trigger: false, passed: [build-candidate], get: version-semver,  resource: version-semver}
      - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
      - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-in}

    - task: test
      file: bosh-cpi-release/ci/tasks/run-lifecycle.yml
      params:
        SL_USERNAME: {{softlayer-username}}
        SL_API_KEY:  {{softlayer-api-key}}

  - name: bats-ubuntu
    serial: true
    plan:
      - aggregate:
        - get: bosh-release
        - get: cpi-release
          resource: bosh-cpi-dev-artifacts
          passed:
            - run-lifecycle
        - {trigger: false, get: stemcell, resource: light-stemcell}
        - get: bosh-cli
        - get: bats
        - get: bosh-deployment
        - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-in}
        - get: version-semver
          trigger: false
          resource: version-semver
          passed:
            - run-lifecycle
        - {put: environment, params: {acquire: true}}

      - do:
        - <<: *deploy-director

        - <<: *prepare-bats-config
          params:
            <<: *prepare-bats-params

        - <<: *run-bats
        ensure:
          do:
          - <<: *teardown
          - {put: environment, params: {release: environment}}

  - name: promote-candidate
    plan:
    - aggregate:
      - {trigger: true,  get: bosh-cpi-dev-artifacts, passed: [bats-ubuntu]}
      - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-in}
      - {trigger: false, get: version-semver,  resource: version-semver, passed: [bats-ubuntu]}

    - task: promote
      file: bosh-cpi-release/ci/tasks/promote-candidate.yml
      params:
        S3_ACCESS_KEY_ID:     {{stemcell-aws-access-key}}
        S3_SECRET_ACCESS_KEY: {{stemcell-aws-secret-key}}

    - put: bosh-cpi-release-out
      params: {repository: promoted/repo, rebase: true, tag_prefix: "v", tag: promoted/integer_version}

    - put: bosh-cpi-final-artifacts
      params: {file: promoted/repo/releases/bosh-softlayer-cpi/*.tgz}

resources:
  - name: bosh-release
    type: bosh-io-release
    source:
        repository: cloudfoundry/bosh

  - name: light-stemcell
    type: s3
    source:
      regexp: light-bosh-stemcell-(\d+(\.\d+){1,2})-softlayer-xen-ubuntu-trusty-go_agent\.tgz
      bucket: bosh-softlayer-cpi-stemcells
      access_key_id: {{stemcell-aws-access-key}}
      secret_access_key: {{stemcell-aws-secret-key}}

  - name: bosh-cpi-release-in
    type: git
    source:
      uri: git@github.com:bluebosh/bosh-softlayer-cpi-release.git
      branch: new_sl_with_actions
      private_key: {{github_private_key}}
      ignore_paths:
          - .final_builds/**/*.yml
          - releases/**/*.yml

  - name: version-semver
    type: semver
    source:
      initial_version: 0.0.0
      key:               current-version
      bucket:            {{s3_pipeline_bucket_lite}}
      access_key_id:     {{stemcell-aws-access-key}}
      secret_access_key: {{stemcell-aws-secret-key}}

  - name: bosh-cpi-dev-artifacts
    type: s3
    source:
      regexp: bosh-softlayer-cpi-(\d+(\.\d+){1,2})\.tgz
      bucket: {{s3_pipeline_bucket_lite}}
      access_key_id: {{stemcell-aws-access-key}}
      secret_access_key: {{stemcell-aws-secret-key}}

  - name: bosh-cpi-release-out
    type: git
    source:
      uri: git@github.com:bluebosh/bosh-softlayer-cpi-release.git
      branch: new_sl_with_actions
      private_key: {{github_private_key}}

  - name: bosh-cpi-final-artifacts
    type: s3
    source:
      regexp: bosh-softlayer-cpi-([0-9.]+)\.tgz
      bucket: {{s3_pipeline_bucket_lite}}
      access_key_id: {{stemcell-aws-access-key}}
      secret_access_key: {{stemcell-aws-secret-key}}

  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/bluebosh/bosh-deployment
      branch: softlayer

  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-softlayer-linux-amd64
      bucket: bosh-softlayer-artifacts
      region_name: us-east-1

  - name: bats
    type: git
    source:
      uri: https://github.com/bluebosh/bosh-acceptance-tests
      branch: gocli-bats

  - name: environment
    type: pool
    source:
      pool: softlayer
      uri: git@github.com:bluebosh/bats-concourse-pool.git
      branch: master
      private_key: {{bosh-src-key}}
