// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"bosh-softlayer-cpi/action"
	"sync"
)

type FakeFactory struct {
	CreateStub        func(method string) (action.Action, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		method string
	}
	createReturns struct {
		result1 action.Action
		result2 error
	}
	createReturnsOnCall map[int]struct {
		result1 action.Action
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFactory) Create(method string) (action.Action, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		method string
	}{method})
	fake.recordInvocation("Create", []interface{}{method})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(method)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createReturns.result1, fake.createReturns.result2
}

func (fake *FakeFactory) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeFactory) CreateArgsForCall(i int) string {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].method
}

func (fake *FakeFactory) CreateReturns(result1 action.Action, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 action.Action
		result2 error
	}{result1, result2}
}

func (fake *FakeFactory) CreateReturnsOnCall(i int, result1 action.Action, result2 error) {
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 action.Action
			result2 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 action.Action
		result2 error
	}{result1, result2}
}

func (fake *FakeFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ action.Factory = new(FakeFactory)
